---
- hosts: all
  become: true
  tasks:
    - name: Export My Finance DB(mysql-standalone)
      command: docker exec mysql-standalone /usr/bin/mysqldump -u root --password=password test > backup.sql
      ignore_errors: yes


