---
- hosts: all
  become: true

  tasks:

    - name: stop current running mysql-standalone container
      command: docker stop mysql-standalone
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm mysql-standalone
      ignore_errors: yes

    - name: pull mysql:5.6  image
      command: docker pull mysql:5.6

    - name: create docker container using mysql:5.6 image
      command: docker run --name mysql-standalone -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=test -e MYSQL_USER=sa -e MYSQL_PASSWORD=password -d mysql:5.6

    - name: copy file
      command: docker cp /opt/docker/query.sql mysql-standalone:/

    - name: run bash on mysql-standalone container
      command: docker exec mysql-standalone /bin/sh -c 'mysql -u sa -ppassword -h127.0.0.1 </query.sql'
