---
- hosts: all
  become: true

  tasks:
    - name: build docker image using jar file
      command: docker build . -t my-finance-watcher-1.0.0:latest
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag my-finance-watcher-1.0.0 alperoz/my-finance-watcher-1.0.0

    - name: push image on to dockerhub
      command: docker push alperoz/my-finance-watcher-1.0.0

    - name: remove docker images from ansible server
      command: docker rmi my-finance-watcher-1.0.0:latest alperoz/my-finance-watcher-1.0.0
      ignore_errors: yes
