# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package and Test with Maven and then push&deploy the image
on:
  push:
  pull_request:
    types: [ opened, reopened ]
    branches: [ master, main ]
jobs:
  build-and-deploy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      REPO: my-finance-watcher-1.0.0
    steps:      
      - run: sudo systemctl start docker
      - run: echo whoami
      - run: whoami
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify -Dmaven.test.skip=true
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package 
          path: staging
      - name: Login into Remote Docker HUB with DockerHub Token...
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Building Dockerfile...  
        run: sudo docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest
      - name: Tagging the image...
        run: sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}
      - name: Pushing the image into Docker Hub... 
        run: sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}
      - name: Removing docker images from Local Server..
        run: sudo docker rmi ${{ env.REPO }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-finance-watcher-1.0.0
      - name: Stoping Current running container
        run: sudo docker stop ${{ env.REPO }}
      - name: Removing stopped container
        run: sudo docker rm ${{ env.REPO }}
      - name: Removing Docker image (${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest)
        run: sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest
      - name: Pulling docker image from duckerhub
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest
      - name: Creating container using ${{ env.REPO }}
        run: sudo docker run -p 8089:8089 --name ${{ env.REPO }} --link mysql-standalone:mysql -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest 
      
       
        
        
        


