# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package and Test with Maven and then push&deploy the image
on:
  push:
  pull_request:
    types: [ opened, reopened ]
    branches: [ master, main ]
jobs:
  build-and-deploy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      REPO: my-finance-watcher-1.0.0
    steps:      
      - run: sudo systemctl start docker
      - run: echo whoami
      - run: whoami
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify -Dmaven.test.skip=true
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package 
          path: staging
      - name: Login into Docker HUB with DockerHub Token...
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - run: sudo docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest
      - run: sudo docker tag ${{ env.REPO }} alperoz/${{ env.REPO }}        
      - run: sudo docker push alperoz/${{ env.REPO }}


