# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package and Test with Maven
on:
  push:
  pull_request:
    types: [ opened, reopened ]
    branches: [ master, main ]
jobs:
  build-and-deploy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify -Dmaven.test.skip=true
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package 
          path: staging
  docker-login:
          env:
            DOCKER_USER:${{secrets.DOCKER_USER}}
            DOCKER_:${{secrets.DOCKER_USER}}
          run:
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  docker push: 
          env:
            REPO: my-finance-watcher-1.0.0
          run: |
            docker build -t $REPO .
            docker tag $REPO:latest ${{secrets.DOCKER_USER}}/$REPO:latest
            docker push ${{secrets.DOCKER_USER}}/$REPO
            
  
            
            
            
            